### ISSUE TITLE
can't find the method: 'initializeReflectable();'

### ISSUE THREAD

**Issue by bladeofgod** [google/reflectable.dart#218]

**Comment by eernstg** [comment]
The code that calls `initializeReflectable()` needs to import the generated code, e.g., `my_main.dart` should import `my_main.reflectable.dart`.

**Comment by bladeofgod** [comment]
> The code that calls `initializeReflectable()` needs to import the generated code, e.g., `my_main.dart` should import `my_main.reflectable.dart`.

thanks a lot
