### ISSUE TITLE
Could not find a file named "pubspec.yaml" in "C:\Users\***\AppData\Roaming\Pub\Cache\hosted\pub.flutter-io.cn\_fe_analyzer_shared-4.0.0".

### ISSUE THREAD

**Issue by bladeofgod** [google/reflectable.dart#219]
when i run 'pub run build_runner build web', the log shows:

'Could not find a file named "pubspec.yaml" in "C:\Users\***\AppData\Roaming\Pub\Cache\hosted\pub.flutter-io.cn\_fe_analyzer_shared-4.0.0".'

**Comment by eernstg** [comment]
The pub cache should contain packages, and each of them should have a `pubspec.yaml` in its root directory. Looks like your cache got damaged. You could try to delete that directory or the whole cache.

**Comment by bladeofgod** [comment]
> The pub cache should contain packages, and each of them should have a `pubspec.yaml` in its root directory. Looks like your cache got damaged. You could try to delete that directory or the whole cache.

thanks your reply.
i just dependency 'reflectable: ^2.2.5' in my pubspec.yaml , should i take '_fe_analyzer_shared-4.0.0'  too ? thanks.

**Comment by eernstg** [comment]
No, you generally shouldn't depend explicitly on packages that your software doesn't depend on directly (if the indirect dependency goes away then you'll have a spurious dependency).

**Comment by bladeofgod** [comment]
> No, you generally shouldn't depend explicitly on packages that your software doesn't depend on directly (if the indirect dependency goes away then you'll have a spurious dependency).

ok, thanks for your help. ;)

**Comment by bladeofgod** [comment]
> No, you generally shouldn't depend explicitly on packages that your software doesn't depend on directly (if the indirect dependency goes away then you'll have a spurious dependency).

sorry to bother you .
my real cache location at  d:flutter\flutter.....\cache\hosted\pub.flutter-io.cn\,
but i run 'pub run ...' in AS terminal ，it point 'C:\Users\***\AppData\Roaming\Pub\Cache\hosted\pub.flutter-io.cn', (cause the error)
how should redirect it ?  thanks.
