### ISSUE TITLE
Update analyzer dependency. 

### ISSUE THREAD

**Issue by Screech129** [google/reflectable.dart#221]
Currently only supports analyzer >=0.39.4 <=0.39.10 but current version is at least ^0.39.11. This makes it incompatible with the other packages that use the newer analyzer.

**Comment by eernstg** [comment]
Thanks for reporting! It is part of https://github.com/google/reflectable.dart/pull/220 to widen the analyzer constraint to 0.39.17, so I'll close this issue because it is being done already.
