### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by mit-mit** [google/reflectable.dart#229]

**Comment by eernstg** [comment]
Plan: Publish `3.0.0-nullsafety.0` as follows:

Migrate the following to null safety:

```
reflectable.dart
capability.dart
mirrors.dart
src/reflectable_builder_based.dart
src/reflectable_class_constants.dart
src/encoding_constants.dart
src/incompleteness.dart
src/reflectable_base.dart
```

such that generated code with null safety is supported. Update `src/builder_implementation.dart` to generate code with null safety. Mark the remaining libraries as `// @dart=2.9`, awaiting migration of the analyzer and other dependencies:

```
reflectable_builder.dart
src/builder_implementation.dart
src/element_capability.dart
src/fixed_point.dart
src/reflectable_errors.dart
```

**Comment by mit-mit** [comment]
That plan sounds great @eernstg !

**Comment by cedvdb** [comment]
the dart_json_mapper library is waiting for the stable release of null safety support (in the issue mentioned above). Maybe it's worth making it stable as to not block null safety support in packages that rely on this. Since I didn't notice that much activity lately on this, I fear it could have been forgotten.

**Comment by mit-mit** [comment]
@eernstg can we go ahead and publish a stable version of this now? The most recent release is still a pre-release: https://pub.dev/packages/reflectable/versions/3.0.0-nullsafety.1

**Comment by Fox32** [comment]
We noticed that we run into trouble with the current `logging` version used by `reflectable` as it isn't referencing `1.0.0` yet. I think that should be fixed before moving to a stable version.

**Comment by eernstg** [comment]
I made some experiments today. Lots of updates, 115 broken tests, so it isn't done immediately. I'll return to this later this week.

**Comment by eernstg** [comment]
https://github.com/google/reflectable.dart/pull/237 under review.

**Comment by eernstg** [comment]
Reflectable 3.0.0 has been published. Closing.
