### ISSUE TITLE
nullsafety version solving failed: Because reflectable 3.0.0-nullsafety.1 depends on logging ^0.11.2

### ISSUE THREAD

**Issue by peterweb2005** [google/reflectable.dart#236]
providing that logging only nullsafety in 1.0.0

**Comment by jiechic** [comment]
me too

**Comment by peterweb2005** [comment]
Well

Because few reactors
And i haven't found any "fork and fix" version
Does the others have "clone and fix" solution?

**Comment by eernstg** [comment]
I just performed a brief experiment with a proper null-safety version (3.0.0 rather than 3.0.0-nullsafety.X). It involves lots of updated versions of other packages, and breaks 115 tests. I can't go further right now, but I'll return to it later this week.

**Comment by eernstg** [comment]
Issue #229 is already concerned with the update of reflectable to a stable version with null safety, so I'll close this one as a duplicate.

You can try out the 3.0.0 PR, to see if it solves your issues: https://github.com/google/reflectable.dart/pull/237.
