### ISSUE TITLE
Reflectable is not considered to have full null safety

### ISSUE THREAD

**Issue by eernstg** [google/reflectable.dart#238]
Cf. https://github.com/dart-lang/pub/issues/2920, pub.dev lists [reflectable](https://pub.dev/packages/reflectable/score) 3.0.0 as _not_ supporting sound null safety.

The code generator cannot yet be migrated (it depends on several packages that aren't migrated), but client programs can be fully null safe, because they are only expected to import some of the libraries in this package, and they all support sound null safety.

**Comment by k-paxian** [comment]
As well this [line](https://github.com/google/reflectable.dart/blob/4ff0143f1e28fc60baacc6946a50ced8ba5cf7fe/reflectable/lib/src/element_capability.dart#L4) prevents from publishing dependent package.

![image](https://user-images.githubusercontent.com/18071010/111540112-00d4d580-876f-11eb-9408-136d40aa00c6.png)

**Comment by eernstg** [comment]
Right, but those language version directives cannot be removed at this point without violating the ordering constraints on null-safety migration, for instance: `lib/reflectable_builder.dart` has `// @dart = 2.9` because it imports `package:build_config/build_config.dart`, which is not available in a version with null safety.

But the point is that reflectable libraries which are imported into client programs are fully null safe, it is only the code generator that isn't yet fully migrated. So client programs can also be fully null safe.

**Comment by peterweb2005** [comment]
i had to change version to "any" in order to run

```
  analyzer: any
  build_resolvers: any
  build_runner: any
  dart_style: any
  glob: any
  logging: any
  package_config: any
  path: ^1.8.0-nullsafety
  source_span: ^1.8.0-nullsafety
```

**Comment by eernstg** [comment]
@peterweb2005, I'm not quite sure what you mean, could you give more details?

**Comment by peterweb2005** [comment]
Yes, those any version previously not nullsafety
So my project referenced to my library reference ro a reflectble library, cant resolve nullsafety version of thoses, eg: analyzer

so i hard to clone reflectable  and edit the versions to any

**Comment by eernstg** [comment]
@peterweb2005, did 3.0.1 resolve the version solving failure that you encountered?

**Comment by peterweb2005** [comment]
> @peterweb2005, did 3.0.1 resolve the version solving failure that you encountered?

can run, thanks

**Comment by buzzware** [comment]
This is holding up my app's null safety via dart-json-mapper

**Comment by eernstg** [comment]
Cf. https://github.com/google/reflectable.dart/pull/248.

**Comment by eernstg** [comment]
As of [3.0.2](https://pub.dev/packages/reflectable), reflectable is now considered to fully support null safety.
