### ISSUE TITLE
Please give more detail document, thks

### ISSUE THREAD

**Issue by xudjx** [google/reflectable.dart#239]

**Comment by eernstg** [comment]
Did you take a look at the [README](https://github.com/google/reflectable.dart/tree/master/reflectable) file, and [TheDesignOfReflectableCapabilities.md](https://github.com/google/reflectable.dart/blob/master/reflectable/doc/TheDesignOfReflectableCapabilities.md)?

**Comment by eernstg** [comment]
I'll close this issue because of the lack of detail. @xudjx, please submit a fresh issue with more detail if needed.
