### ISSUE TITLE
update dart_style 2.0.0 for null safely

### ISSUE THREAD

**Issue by jiechic** [google/reflectable.dart#240]
`Because no versions of retrofit_generator match >2.0.0-beta2 <3.0.0 and retrofit_generator 2.0.0-beta2 depends on dart_style ^2.0.0, retrofit_generator ^2.0.0-beta2 requires dart_style ^2.0.0.
Because reflectable 3.0.0 depends on dart_style ^1.3.0 and no versions of reflectable match >3.0.0 <4.0.0, reflectable ^3.0.0 requires dart_style ^1.3.0.
Thus, retrofit_generator ^2.0.0-beta2 is incompatible with reflectable ^3.0.0.
And because dart_json_mapper 2.0.5 depends on reflectable ^3.0.0 and no versions of dart_json_mapper match >2.0.5 <3.0.0, retrofit_generator ^2.0.0-beta2 is incompatible with dart_json_mapper ^2.0.5.
So, because okki_flutter depends on both dart_json_mapper ^2.0.5 and retrofit_generator ^2.0.0-beta2, version solving failed.
pub get failed (1; So, because okki_flutter depends on both dart_json_mapper ^2.0.5 and retrofit_generator ^2.0.0-beta2, version solving failed.)`

update dart_style to 2.0.0 for null safely

**Comment by eernstg** [comment]
We can do that: #241.

**Comment by eernstg** [comment]
`reflectable` 3.0.1 published, using `dart_style` ^2.0.0.
