### ISSUE TITLE
Not nullable var on SuperclassQuantifyCapability

### ISSUE THREAD

**Issue by ChamplainLeCode** [google/reflectable.dart#243]
```bash
[WARNING] stderr: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/reflectable-3.0.1/lib/src/element_capability.dart:210:67: Error: The value 'null' can't be assigned to the parameter type 'Element' because 'Element' is not nullable.
[WARNING] stderr:  - 'Element' is from 'package:analyzer/dart/element/element.dart' ('/opt/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.3.0/lib/dart/element/element.dart').
[WARNING] stderr: const superclassQuantifyCapability = SuperclassQuantifyCapability(null);
[WARNING] stderr:                                                                   ^
[INFO] Creating build script snapshot... completed, took 5.8s

[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
```

at line 202 of **reflectable-3.0.1/lib/src/element_capability.dart** setup **upperBound** as nullable.

**Comment by eernstg** [comment]
Why would you want to use `null` as the bound? `null` isn't actually a superclass of any class.

**Comment by ChamplainLeCode** [comment]
I'm using reflectable in my plugin to help me to make reflexion on my classes. 

My plugin was running before on reflectable 2.0.0, Now I decided to upgrate to dart min sdk 2.12.0, after updrading all dependencies, reflectable (3.0.1) build (2.0.0) source_gen... I got error above when I ran **flutter packages pub run build_runner build --delete-conflicting-outputs**. When I update declaration of upperBound to **Element? upperBound** it works perfectly

**Comment by ChamplainLeCode** [comment]
at line 202 of **reflectable-3.0.1/lib/src/element_capability.dart**

**Comment by eernstg** [comment]
@ChamplainLeCode, this is rather confusing. ;-)

In particular, it is surprising that there can be the error `The value 'null' can't be assigned to the parameter type 'Element' because 'Element' is not nullable` in 'lib/src/element_capability.dart'.

That should never happen, because that library contains the directive `// @dart = 2.9`, and hence the code in that library doesn't use null safety (and hence we should also get a compile-time error if we ever put a type like `Element?` in there).

I don't see the error reported [here](https://github.com/google/reflectable.dart/issues/243#issue-843139347) when I try out https://github.com/eernstg/reflectable-flutter (and it runs as expected).

Did you make any changes to reflectable, e.g., by deleting the `// @dart = 2.9` directive from 'lib/src/element_capability.dart'?

**Comment by ChamplainLeCode** [comment]
As you can see, the `// @dart = 2.9` directive is still there.
![image](https://user-images.githubusercontent.com/26502711/112912194-df6cd580-90ee-11eb-9219-85595c9b765e.png)

This is my pubspec.yaml
![image](https://user-images.githubusercontent.com/26502711/112912645-ecd68f80-90ef-11eb-90a7-a2e4c4629746.png)

You can see that I upgraded my min sdk to `v2.12.0`

**Comment by eernstg** [comment]
> the `// @dart = 2.9` directive is still there.

Thanks! I'm currently trying to get an explanation about how such a library could ever be treated as if it were opting in to use null safety.

**Comment by jakemac53** [comment]
This looks similar to https://github.com/dart-lang/build/issues/3046 possibly, although slightly different. The error here is during the snapshotting process - not the build itself - so it is not likely a package:build issue but a more general tooling issue of some sort.

**Comment by jakemac53** [comment]
@ChamplainLeCode do you have any dependency overrides? You could also try doing a `pub cache repair` (although this will take a long time and use a lot of bandwidth so fair warning).

**Comment by eernstg** [comment]
Thanks, @jakemac53!

**Comment by eernstg** [comment]
One more remark from @jakemac53: Try deleting `/opt/flutter/.pub-cache` in order to force the use of the normal pub cache.

**Comment by sibylantoninobajeli** [comment]
The deleting of /flutter/.pub-cache resolved my problem.
Thanks to @jakemac53!

**Comment by ChamplainLeCode** [comment]
After clearing cache, it solved my problem 😎
