### ISSUE TITLE
Is it possible to ignore a field when generating fields for a class?

### ISSUE THREAD

**Issue by cyberpwnn** [google/reflectable.dart#247]
```dart
class SomeClass {
    int a = 3;
    int b = 4;

    // Don't generate any reflective code for this
    int someTransientProperty = 39;
}
```

Is there an annotation or way to configure this? For the most part it's becasue of flutter state management and I dont want ui components getting jammed into the main.reflect file. (build fails when it includes certain fields that i dont even need)

**Comment by eernstg** [comment]
The selection of members with reflection support is controlled by _inclusion_ capabilities (like "include all members" or "include each member whose name matches the following regexp"), there is no way to selectively specify that  certain members should be _excluded_. You can express the same thing, of course, but it can get somewhat verbose:

```dart
class DoReflect { const DoReflect(); }
const doReflect = DoReflect();

class Reflector extends Reflectable {
  const Reflector() : super(const InstanceInvokeMetaCapability(DoReflect));
}
const reflector = Reflector();

@reflector
class SomeClass {
    @doReflect int a = 3;
    @doReflect int b = 4;

    // Don't generate any reflective code for this: Omit `@doReflect`.
    int someTransientProperty = 39;
}
```

See https://github.com/google/reflectable.dart/blob/master/test_reflectable/test/member_capability_test.dart for a complete example where this feature is used.

**Comment by cyberpwnn** [comment]
An Ignore annotation or exclusive means would be fantastic, however this is good enough. I'll close this.
