### ISSUE TITLE
Problem when build web release package(v3.0.4 with flutter 2.2.3)

### ISSUE THREAD

**Issue by cardinalblues7** [google/reflectable.dart#259]
It was fine when in debug mode, as well as the release mode on Android App.But for the Web platform, when we built for release, we were surprised that all the reflectables not working at all!, then I tried profile mode, works fine again. By "not working", I put some sample code as below to show this:

Sample code:

```
class ClassInstantiateReflectable extends Reflectable {
  const ClassInstantiateReflectable() : super(newInstanceCapability, reflectedTypeCapability, instanceInvokeCapability, declarationsCapability, metadataCapability, topLevelInvokeCapability, typeRelationsCapability, typeCapability, typeAnnotationQuantifyCapability, staticInvokeCapability);//, typeAnnotationQuantifyCapability
}

const classInstantiateReflectable = const ClassInstantiateReflectable();

@classInstantiateReflectable
class LawModel extends AbstractModel
{
    late int id; // works fine
    late String name; // works fine
   DateTime? validationDate; // not working, failed to reflect this field
   LawCategory? category; // not working, failed to reflect this field(Custom class)
  
   FileObject? file;// not working, failed to reflect this field(Custom class)
}
```

Interestingly, I found that it's all working when debug and profile, but not release.I suspected that it has to have something to do with the minification process. Does it have any work arounds to fix this ?

**Comment by cardinalblues7** [comment]
Any one could help?

**Comment by cardinalblues7** [comment]
Finally figured it out. For someone may find this useful, In my code there is one place to check the type string then do some action .In release mode, everything is automatically renamed, then the type name comparison would not work. After changing the type string compare to simple type compare, it works well.

**Comment by eernstg** [comment]
Thanks for the information, it could help others!

I'm not quite sure what you mean by 'type string', but if it is `myType.toString()` where `myType` is an instance of `Type` then it will certainly fail to compare with a string literal (say, `'SomeClass'`) if the compilation includes a minification step. You're right that the simple comparison `myType == SomeClass` is the preferred approach, minification or not.
