### ISSUE TITLE
How to calling a global function with reflectable?

### ISSUE THREAD

**Issue by RicoLiu** [google/reflectable.dart#271]
eg:
```dart
jsonDecode('{"name": "test"}');
```

How to call `jsonDecode` with reflectable?

**Comment by eernstg** [comment]
[Here](https://github.com/google/reflectable.dart/blob/d86b67fa4912bff98cef9e5fd9e2313ff7857c3b/test_reflectable/test/libraries_test.dart#L74) is an example showing how a top-level function can be called reflectively.

**Comment by RicoLiu** [comment]
> [Here](https://github.com/google/reflectable.dart/blob/d86b67fa4912bff98cef9e5fd9e2313ff7857c3b/test_reflectable/test/libraries_test.dart#L74) is an example showing how a top-level function can be called reflectively.

thank you.
