### ISSUE TITLE
Depth of Reflection

### ISSUE THREAD

**Issue by viniciusandd** [google/reflectable.dart#282]
I have a scenario where many classes (widgets) will be reflected. My goal is to get the types of attributes of these classes. The amount of classes I intend to reflect requires my regex to be flexible and the consequence is the reflection of many unnecessary classes.

I believe that defining depth for reflection would solve my problem. Is there any way to do this?

**Comment by eernstg** [comment]
> depth for reflection

What would that mean?

**Comment by viniciusandd** [comment]
Basically delimit the generated reflections.

An example would be generating `A` (I want its attributes) and `B` (as it is the type of the `secondAttr` attribute). But ignore C, as I won't be using B's attributes.

```dart
class A {
  final int firstAttr;
  final B secondAttr;
}

class B {
  final C anyAttr;
}

class C {
  ...
}
```

In my use case I have control over the classes involved, but not over all types of attributes present in them.

This lack of predictability prevents me from controlling reflections through `GlobalQuantifyCapability`.

I can't replicate what you did [here](https://github.com/google/reflectable.dart/blob/master/test_reflectable/test/global_quantify_test.dart)
