### ISSUE TITLE
Bug: Reflectable doesn't work with latest analyzer 4.4.0 package

### ISSUE THREAD

**Issue by zottel4242** [google/reflectable.dart#286]
A few days ago analyzer 4.4.0 was released.  Reflectable doesn't seem to be compatible with it. It causes the following error on my machines (Windows, Linux):

```
Building package executable...
Built build_runner:build_runner.
[INFO] Generating build script completed, took 314ms
[WARNING] ../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/reflectable-3.0.9/lib/src/builder_implementation.dart:5317:11: Error: No named parameter with the name 'element'.
          element: this,
../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/analyzer-4.4.0/lib/src/dart/element/type.dart:451:3: Context: Found this candidate, but the arguments don't match.
  InterfaceTypeImpl({
  ^^^^^^^^^^^^^^^^^
[INFO] Precompiling build script... completed, took 1.1s
[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
```

I now use the workaround to force analyzer to 4.3.1 in the pubspec.yaml of my project:
`analyzer: 4.3.1`

**Comment by eernstg** [comment]
Thanks for reporting this! The analyzer had a number of breaking changes, so the migration to 4.4.0 will not be coming immediately. Hopefully in a week or two, depending on the number of opportunities I get to look at it.

**Comment by AdamNSmith** [comment]
Bump. Still seeing this issue.

**Comment by eernstg** [comment]
The work is ongoing, cf. https://github.com/google/reflectable.dart/pull/288.
