### ISSUE TITLE
Get annotation from enum field

### ISSUE THREAD

**Issue by lucas404x** [google/reflectable.dart#291]
My goal is to create a Description annotation for enums (something like "DescriptionAttribute" that exists on C#). I try the code below but the "metadata" returns always empty. 

```dart
class Description {
  const Description(this.value);

  final String value;
}

@reflector
enum Example {
  @Description("A")
  a,
  @Description("B")
  b
}


void main() {
  initializeReflectable();

  var val = Example.a;
  var instanceMirror = reflector.reflect(val);
  var variableMirror = instanceMirror.type.declarations[val.name] as VariableMirror;
  print(variableMirror.metadata.length); // 0
}
```

But if I replace the enum for a class, it works perfectly.

```dart
class Description {
  const Description(this.value);

  final String value;
}

@reflector
class Example {
  const Example(this.a);

  @Description("a")
  final String a;
}


void main() {
  initializeReflectable();

  var val = const Example("A");
  var instanceMirror = reflector.reflect(val);
  var variableMirror = instanceMirror.type.declarations["a"] as VariableMirror;
  print(variableMirror.metadata.length); // 1
}
```

Am I doing something wrong or is there another way to achieve this objective? Or should I use dart:mirrors directly?

**Comment by lucas404x** [comment]
Thanks for your suggestion @eernstg ! 
I'm following another approach using interfaces and extension methods because as like C# I want it works in any kind of environment, specifically in generic functions/methods.

**Comment by eernstg** [comment]
Fixed in https://github.com/google/reflectable.dart/pull/334.
