### ISSUE TITLE
【macos】Attempt to `invoke` without class mirrors.

### ISSUE THREAD

**Issue by anql** [google/reflectable.dart#294]
Flutter 3.3.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 6928314d50 (3 days ago) • 2022-10-25 16:34:41 -0400
Engine • revision 3ad69d7be3
Tools • Dart 2.18.2 • DevTools 2.15.0

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: *** Unexpected situation encountered!
Please report a bug on github.com/dart-lang/reflectable: Attempt to `invoke` without class mirrors.
#0      unreachableError (package:reflectable/src/incompleteness.dart:30:3)
#1      _InstanceMirrorImpl.invoke (package:reflectable/src/reflectable_builder_based.dart:260:13)
#2      ModuleManager.invoke (package:plugin_ffi_engine/ajx/modules/ModuleManager.dart:122:34)
#3      JsContext.invoke (package:plugin_ffi_engine/ajx/JsContext.dart:97:19)
#4      NativeModuleDefinition_call (package:plugin_ffi_engine/ajx/core/native_module_definition.dart:24:13)
#5      MessageNativeModuleCall.call (package:plugin_ffi_engine/amap_ffi_msg_native_module.dart:16:7)
#6      MainIsolateMsgListener.listen.<anonymous closure> (package:plugin_ffi_engine/amap_ffi_msg_listener.dart:44:14)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#11     _StreamController._add (dart:async/stream_controller.dart:648:7)
#12     _StreamController.add (dart:async/stream_controller.dart:596:5)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

**Comment by eernstg** [comment]
Thanks!

Can you provide some more information about how this situation can be recreated? It would be great to have reproduction program that doesn't depend on large amounts of software like Flutter.
