### ISSUE TITLE
Where is initializeReflectable method?

### ISSUE THREAD

**Issue by ChrisCoy** [google/reflectable.dart#321]
I am trying to set up reflectable, and I cannot find any definition of initializeReflectable. I have also looked in the source code but couldn't find anything about it. All I found was the error message that tells me to run initializeReflectable first.

I am using Visual Studio Code, and it gives the following error: 
`The function 'initializeReflectable' isn't defined. Try importing the library that defines 'initializeReflectable', correcting the name to the name of an existing function, or defining a function named 'initializeReflectable'.dart[undefined_function](https://dart.dev/diagnostics/undefined_function)`

I've tried older versions as well (2.x.x), but still the same.

You can find my code at: [https://github.com/ChrisCoy/vvalidator/tree/reflectable_error](url)

**Comment by eernstg** [comment]
`initializeReflectable` is declared in the generated library. If your entry point is `lib/main.dart` then the generated library would be `lib/main.reflectable.dart` and you would need to have `import 'main.reflectable.dart';` in your 'main.dart'.

Similarly, if your entry point is `bin/whatever.dart` then the generated library would be `bin/whatever.reflectable.dart` and you'd need to import the generated library from `bin/whatever.dart`.

The example code does not seem to have any occurrences of such imports.

**Comment by ChrisCoy** [comment]
I see, sorry for opening this useless issue, thank you!

**Comment by eernstg** [comment]
No problem, of course&mdash;I think it's a valuable property of the community if all good-faith questions can be asked freely! ;-)
